import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/csr">
            <div className={styles.card}>
              <h2>CSR &rarr;</h2>
              <p>Client Side Rendering</p>
            </div>
          </Link>

          <Link href="/ssg">
            <div className={styles.card}>
              <h2>SSG &rarr;</h2>
              <p>Static Site Generation</p>
            </div>
          </Link>

          <Link href="/isr">
            <div className={styles.card}>
              <h2>ISR &rarr;</h2>
              <p>Incremental Static Regeneration</p>
            </div>
          </Link>

          <Link href="/ssr">
            <div className={styles.card}>
              <h2>SSR &rarr;</h2>
              <p>Server Side Rendering</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
